version: '3'
services:
    web:
        image: 'scr12/nginx-np:71'
        ports:
            - "1995:80"
        restart: always
        container_name: 'web'
        volumes:
            - "./hosts:/home/nginx/"
            - "./vhosts:/etc/nginx/vhosts.d/"
