version: '3'
services:
    web:
        image: 'scr12/nginx-np:71'
        ports:
            - "80:80"
            - "443:443"
        restart: always
        container_name: 'web'
        volumes:
            - "./hosts:/home/nginx/"
            - "./vhosts:/etc/nginx/vhosts.d/"
            - "./files/default.conf:/etc/nginx/conf.d/default.conf"
            - "./files/self-signed.conf:/etc/nginx/snippets/self-signed.conf"
            - "./files/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf"
            - "./certs/dhparam.pem:/etc/ssl/certs/dhparam.pem"
            - "./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt"
            - "./certs/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key"
    mongo:
        image: "mongo"
        container_name: "mongo"
        hostname: "mongo"
        ports:
            - "27017:27017"
        volumes:
            - $PWD/mongo/data:/data/db
