version: "2"

services:
  lanserver:
    image: aiotrc/lanserver
    restart: always
    environment:
      - PORT=4000
      - ADDR=0.0.0.0
      - DB_URL=mongodb://127.0.0.1:27017
      - BROKER_URL=tcp://127.0.0.1:1883
    ports:
      - 4000:4000
