version: "2"

services:
  lanserver:
    image: aiotrc/lanserver
    restart: always
    environment:
      - PORT=4000
      - ADDR=0.0.0.0
      - DB_URL=mongodb://172.17.0.1:27017
    ports:
      - 4000:4000
