version: "3"

services:
  lanserver:
    image: i1820/lanserver
    restart: always
    environment:
      - PORT=4000
      - ADDR=0.0.0.0
      - DB_URL=mongodb://127.0.0.1:27017
      - NODE_BROKER_URL=tcp://127.0.0.1:1883
      - APPLICATION_BROKER_URL=tcp://127.0.0.1:1883
      - NODE_SECRET=
    ports:
      - 4000:4000
