kind: Service
apiVersion: v1
metadata:
  name: mongo-express
  namespace: i1820
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: mongo-express
