version: "2"

services:
  loraserver:
    ports:
      - 8000:8000
    environment:
      - GW_MQTT_SERVER=tcp://mosquitto:1883

  appserver:
    ports:
      - 8080:8080
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883

  postgresql_ns:
    volumes:
      - ./postgresql/ns/data:/var/lib/postgresql/data

  postgresql_as:
    volumes:
      - ./postgresql/as/data:/var/lib/postgresql/data

  gatewaybridge:
    ports:
      - 1700:1700/udp
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883

  mosquitto:
    ports:
      - 9001:9001
      - 1883:1883
