version: "2"

services:
  uplink:
    image: aiotrc/uplink
    environment:
      - broker_url=172.23.132.52:1883
      - db_url=172.17.0.1
      - decoder_host=172.17.0.1
      - pm_url=http://172.17.0.1:8080
