version: "2"

services:
  uplink:
    image: aiotrc/uplink
    restart: always
    environment:
      - BROKER_URL=172.17.0.1:1883
      - DB_URL=mongodb://172.17.0.1
      - PM_URL=http://172.17.0.1:8080
      - TZ=Asia/Tehran
